# -*- coding: utf-8 -*-
"""(Md Ahsan 479918) Project II: Patient Health Monitoring & Appointment Management System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRQ9ngMKXZNdGpsVOkFKRclF3tfih806
"""

class Patient:
    def __init__(self, name, age, gender, contact, conditions):
        self.name = name
        self.age = age
        self.gender = gender
        self.contact = contact
        self.conditions = conditions


class HospitalSystem:
    def __init__(self):
        self.patients = []

    def add_patient(self):
        name = input("Name: ")
        age = int(input("Age: "))
        gender = input("Gender: ")
        contact = input("Contact: ")
        conditions = input("Health conditions (comma separated): ").split(",")

        self.patients.append(Patient(name, age, gender, contact, [c.strip() for c in conditions]))
        print("Patient added!\n")

    def search(self, name):
        for p in self.patients:
            if p.name.lower() == name.lower():
                return p
        return None

    def update_patient(self):
        name = input("Enter name to update: ")
        p = self.search(name)
        if not p:
            print("Not found!\n")
            return

        p.name = input("New name (press enter to skip): ") or p.name
        new_age = input("New age: ")
        p.age = int(new_age) if new_age else p.age
        p.gender = input("New gender: ") or p.gender
        p.contact = input("New contact: ") or p.contact

        new_cond = input("New health conditions: ")
        if new_cond:
            p.conditions = [c.strip() for c in new_cond.split(",")]

        print("Updated!\n")

    def delete_patient(self):
        name = input("Enter name to delete: ")
        p = self.search(name)
        if p:
            self.patients.remove(p)
            print("Patient deleted!\n")
        else:
            print("Not found!\n")

    def display_all(self):
        if not self.patients:
            print("No patients.\n")
            return
        for p in self.patients:
            print(f"{p.name} | {p.age} | {p.gender} | {p.contact} | {', '.join(p.conditions)}")
        print()


def main():
    system = HospitalSystem()

    while True:
        print("1.Add  2.Search  3.Update  4.Delete  5.Display  6.Exit")
        choice = input("Choice: ")

        if choice == "1":
            system.add_patient()
        elif choice == "2":
            name = input("Enter name: ")
            p = system.search(name)
            if p:
                print(f"{p.name} | {p.age} | {p.gender} | {p.contact} | {', '.join(p.conditions)}\n")
            else:
                print("Not found!\n")
        elif choice == "3":
            system.update_patient()
        elif choice == "4":
            system.delete_patient()
        elif choice == "5":
            system.display_all()
        elif choice == "6":
            break
        else:
            print("Invalid!\n")


main()

from datetime import datetime

class Patient:
    def __init__(self, name):
        self.name = name
        self.vitals_history = []   # list of all vitals records

    def add_vitals(self, temp, bp, heart, weight):
        date = datetime.now().strftime("%Y-%m-%d")
        vitals = {
            "date": date,
            "temperature": temp,
            "blood_pressure": bp,
            "heart_rate": heart,
            "weight": weight
        }
        self.vitals_history.append(vitals)
        print("Vitals added!\n")

    def show_vitals(self):
        if not self.vitals_history:
            print("No vitals recorded yet.\n")
            return

        print(f"Vitals history for {self.name}:")
        for v in self.vitals_history:
            print(v)
        print()


class ClinicSystem:
    def __init__(self):
        self.patients = {}

    def add_patient(self):
        name = input("Enter patient name: ")
        self.patients[name] = Patient(name)
        print("Patient added!\n")

    def record_vitals(self):
        name = input("Enter name: ")
        if name not in self.patients:
            print("Patient not found!\n")
            return

        try:
            temp = float(input("Temperature: "))
            bp = input("Blood Pressure (e.g. 120/80): ")
            heart = int(input("Heart Rate: "))
            weight = float(input("Weight: "))
        except:
            print("Invalid input! Please enter correct values.\n")
            return

        self.patients[name].add_vitals(temp, bp, heart, weight)

    def view_vitals(self):
        name = input("Enter name: ")
        if name not in self.patients:
            print("Patient not found!\n")
            return
        self.patients[name].show_vitals()


system = ClinicSystem()

while True:
    print("1. Add Patient")
    print("2. Record Vitals")
    print("3. View Vitals")
    print("4. Exit")

    choice = input("Choose: ")

    if choice == "1":
        system.add_patient()
    elif choice == "2":
        system.record_vitals()
    elif choice == "3":
        system.view_vitals()
    elif choice == "4":
        break
    else:
        print("Invalid choice!\n")

appointments = []   # each appointment is a dictionary

def book_appointment():
    name = input("Patient name: ")

    date = input("Date (YYYY-MM-DD): ")
    time = input("Time (HH:MM): ")
    doctor = input("Doctor name: ")

    # Check if slot already booked
    for a in appointments:
        if a["date"] == date and a["time"] == time:
            print("❌ This time slot is already booked!\n")
            return

    # Save appointment
    appointments.append({
        "name": name,
        "date": date,
        "time": time,
        "doctor": doctor
    })
    print("✔ Appointment booked!\n")


def view_appointments():
    if not appointments:
        print("No appointments found.\n")
        return

    print("\n--- All Appointments ---")
    for a in appointments:
        print(f"{a['date']} {a['time']} | {a['name']} with Dr. {a['doctor']}")
    print()


def cancel_appointment():
    date = input("Enter date (YYYY-MM-DD): ")
    time = input("Enter time (HH:MM): ")

    for a in appointments:
        if a["date"] == date and a["time"] == time:
            appointments.remove(a)
            print("✔ Appointment cancelled!\n")
            return

    print("❌ No appointment found for this slot.\n")


# Menu
while True:
    print("1. Book Appointment")
    print("2. View Appointments")
    print("3. Cancel Appointment")
    print("4. Exit")

    choice = input("Choose: ")

    if choice == "1":
        book_appointment()
    elif choice == "2":
        view_appointments()
    elif choice == "3":
        cancel_appointment()
    elif choice == "4":
        break
    else:
        print("Invalid choice!\n")

# -----------------------
# FILE NAMES
# -----------------------
PATIENT_FILE = "patients.txt"
VITALS_FILE = "vitals.txt"
APPT_FILE = "appointments.txt"

# -----------------------
# LOAD DATA
# -----------------------
def load_file(filename):
    data = []
    # open file in append+read mode (creates file if not exists)
    f = open(filename, "a+")
    f.seek(0)  # move cursor to start
    for line in f:
        line = line.strip()
        if line:
            parts = line.split("|")  # fields separated by |
            data.append(parts)
    f.close()
    return data


# -----------------------
# SAVE DATA
# -----------------------
def save_file(filename, data_list):
    f = open(filename, "w")
    for item in data_list:
        f.write("|".join(item) + "\n")
    f.close()


# -----------------------
# DATA LISTS
# -----------------------
patients = load_file(PATIENT_FILE)
vitals = load_file(VITALS_FILE)
appointments = load_file(APPT_FILE)

def load_file(filename):
    data = []
    try:
        with open(filename, "r") as f:
            for line in f:
                line = line.strip().split("|")
                if len(line) > 1:
                    data.append(line)
    except FileNotFoundError:
        print(f"{filename} not found, creating a new one...\n")
    return data


def save_file(filename, data):
    with open(filename, "w") as f:
        for item in data:
            f.write("|".join(item) + "\n")


# ---------------------------
# LOAD DATA
# ---------------------------
patients = load_file("patients.txt")
vitals = load_file("vitals.txt")
appointments = load_file("appointments.txt")


# ---------------------------
# FUNCTIONS WITH ERROR HANDLING
# ---------------------------
def add_patient():
    name = input("Name: ")

    try:
        age = int(input("Age: "))
    except ValueError:
        print("❌ Invalid age! Must be a number.\n")
        return

    gender = input("Gender: ")
    contact = input("Contact: ")
    conditions = input("Health Conditions (comma separated): ").replace(",", ";")

    patients.append([name, str(age), gender, contact, conditions])
    save_file("patients.txt", patients)
    print("✔ Patient saved!\n")


def add_vitals():
    name = input("Patient Name: ")

    # patient existence check
    if not any(p[0].lower() == name.lower() for p in patients):
        print("❌ Patient not found!\n")
        return

    try:
        temp = float(input("Temperature: "))
        bp = input("Blood Pressure: ")
        hr = int(input("Heart Rate: "))
        weight = float(input("Weight: "))
    except ValueError:
        print("❌ Invalid vital input! Numbers required.\n")
        return

    date = input("Date (YYYY-MM-DD): ")

    vitals.append([name, str(temp), bp, str(hr), str(weight), date])
    save_file("vitals.txt", vitals)
    print("✔ Vitals saved!\n")


def book_appointment():
    name = input("Patient Name: ")
    date = input("Date (YYYY-MM-DD): ")
    time = input("Time (HH:MM): ")
    doctor = input("Doctor Name: ")

    # conflict check
    for a in appointments:
        if a[1] == date and a[2] == time:
            print("❌ Appointment conflict! Slot already booked.\n")
            return

    appointments.append([name, date, time, doctor])
    save_file("appointments.txt", appointments)
    print("✔ Appointment booked!\n")


def search_patient():
    name = input("Enter patient name to search: ")

    for p in patients:
        if p[0].lower() == name.lower():
            print("✔ Patient Found:", p, "\n")
            return

    print("❌ Patient not found!\n")


# ---------------------------
# MENU WITH WRONG CHOICE HANDLING
# ---------------------------
while True:
    print("1. Add Patient")
    print("2. Add Vitals")
    print("3. Book Appointment")
    print("4. Search Patient")
    print("5. Exit")

    choice = input("Choose: ")

    try:
        if choice == "1":
            add_patient()
        elif choice == "2":
            add_vitals()
        elif choice == "3":
            book_appointment()
        elif choice == "4":
            search_patient()
        elif choice == "5":
            print("Exiting...")
            break
        else:
            raise ValueError  # wrong menu choice
    except ValueError:
        print("❌ Invalid menu choice!\n")

def load_file(filename):
    data = []
    try:
        with open(filename, "r") as f:
            for line in f:
                parts = line.strip().split("|")
                if len(parts) > 1:
                    data.append(parts)
    except FileNotFoundError:
        pass
    return data


def save_file(filename, data):
    with open(filename, "w") as f:
        for item in data:
            f.write("|".join(item) + "\n")


# ------------------------------
# LOAD EXISTING DATA
# ------------------------------
patients = load_file("patients.txt")
vitals = load_file("vitals.txt")
appointments = load_file("appointments.txt")


# ------------------------------
# PATIENT FUNCTIONS
# ------------------------------

def add_patient():
    name = input("Name: ")

    try:
        age = int(input("Age: "))
    except ValueError:
        print("Invalid age!\n")
        return

    gender = input("Gender: ")
    contact = input("Contact: ")
    conditions = input("Conditions (comma separated): ").replace(",", ";")

    patients.append([name, str(age), gender, contact, conditions])
    print("Patient added!\n")


def update_patient():
    name = input("Enter patient name to update: ")

    for p in patients:
        if p[0].lower() == name.lower():
            print("Leave blank to keep old value.")

            new_age = input("New Age: ")
            if new_age:
                try:
                    p[1] = str(int(new_age))
                except:
                    print("Invalid age!")

            new_gender = input("New Gender: ")
            if new_gender:
                p[2] = new_gender

            new_contact = input("New Contact: ")
            if new_contact:
                p[3] = new_contact

            new_cond = input("New Conditions: ")
            if new_cond:
                p[4] = new_cond.replace(",", ";")

            print("Updated!\n")
            return

    print("Patient not found!\n")


def view_patients():
    if not patients:
        print("No patients found!\n")
        return

    print("\n--- Patient Records ---")
    for p in patients:
        print(f"{p[0]} | Age:{p[1]} | {p[2]} | {p[3]} | {p[4]}")
    print()


# ------------------------------
# VITALS FUNCTIONS
# ------------------------------

def add_vitals():
    name = input("Patient Name: ")

    if not any(p[0].lower() == name.lower() for p in patients):
        print("Patient not found!\n")
        return

    try:
        temp = float(input("Temperature: "))
        hr = int(input("Heart Rate: "))
        weight = float(input("Weight: "))
    except ValueError:
        print("Invalid input!\n")
        return

    bp = input("Blood Pressure: ")
    date = input("Date (YYYY-MM-DD): ")

    vitals.append([name, str(temp), bp, str(hr), str(weight), date])
    print("Vitals recorded!\n")


def view_vitals():
    if not vitals:
        print("No vitals recorded!\n")
        return

    print("\n--- Vitals History ---")
    for v in vitals:
        print(f"{v[0]} | Temp:{v[1]} | BP:{v[2]} | HR:{v[3]} | Wt:{v[4]} | {v[5]}")
    print()


# ------------------------------
# APPOINTMENT FUNCTIONS
# ------------------------------

def book_appointment():
    name = input("Patient Name: ")

    date = input("Date (YYYY-MM-DD): ")
    time = input("Time (HH:MM): ")
    doctor = input("Doctor Name: ")

    # conflict check
    for a in appointments:
        if a[1] == date and a[2] == time:
            print("Time slot already booked!\n")
            return

    appointments.append([name, date, time, doctor])
    print("Appointment booked!\n")


def view_appointments():
    if not appointments:
        print("No appointments found!\n")
        return

    print("\n--- Appointments ---")
    for a in appointments:
        print(f"{a[0]} | {a[1]} | {a[2]} | Dr.{a[3]}")
    print()


def cancel_appointment():
    name = input("Enter patient name to cancel appointment: ")

    for a in appointments:
        if a[0].lower() == name.lower():
            appointments.remove(a)
            print("Appointment cancelled!\n")
            return

    print("Appointment not found!\n")


# ------------------------------
# MAIN MENU
# ------------------------------

while True:
    print("1. Add Patient")
    print("2. Update Patient")
    print("3. View Patient Records")
    print("4. Track Patient Vitals")
    print("5. View Vitals History")
    print("6. Book Appointment")
    print("7. View Appointments")
    print("8. Cancel Appointment")
    print("9. Save & Exit")

    choice = input("Choose: ")

    if choice == "1":
        add_patient()
    elif choice == "2":
        update_patient()
    elif choice == "3":
        view_patients()
    elif choice == "4":
        add_vitals()
    elif choice == "5":
        view_vitals()
    elif choice == "6":
        book_appointment()
    elif choice == "7":
        view_appointments()
    elif choice == "8":
        cancel_appointment()
    elif choice == "9":
        save_file("patients.txt", patients)
        save_file("vitals.txt", vitals)
        save_file("appointments.txt", appointments)
        print("Data saved! Exiting...")
        break
    else:
        print("Invalid menu choice!\n")

